<div class="grid gap-6 md:grid-cols-2">
    <div class="space-y-2 md:col-span-2"><label class="text-sm font-medium text-slate-700">Judul</label><input type="text" name="title" value="{{ old('title', $project->title) }}" class="w-full rounded-2xl border-slate-200" required></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Kategori</label><input type="text" name="category" value="{{ old('category', $project->category) }}" class="w-full rounded-2xl border-slate-200"></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Cover Image</label><input type="file" name="cover_image" class="w-full rounded-2xl border-slate-200">@if ($project->cover_image)<img src="{{ asset($project->cover_image) }}" alt="cover" class="mt-2 h-24 rounded-xl object-cover">@endif</div>
    <div class="space-y-2 md:col-span-2"><label class="text-sm font-medium text-slate-700">Deskripsi Singkat</label><textarea name="description" rows="3" class="w-full rounded-2xl border-slate-200">{{ old('description', $project->description) }}</textarea></div>
    <div class="space-y-2 md:col-span-2"><label class="text-sm font-medium text-slate-700">Konten</label><textarea name="content" rows="8" class="w-full rounded-2xl border-slate-200">{{ old('content', $project->content) }}</textarea></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Tech Stack</label><input type="text" name="tech_stack" value="{{ old('tech_stack', $project->tech_stack) }}" class="w-full rounded-2xl border-slate-200" placeholder="Laravel, Tailwind, MySQL"></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Status</label><select name="status" class="w-full rounded-2xl border-slate-200"><option value="draft" @selected(old('status', $project->status) === 'draft')>Draft</option><option value="published" @selected(old('status', $project->status) === 'published')>Published</option></select></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Demo URL</label><input type="url" name="demo_url" value="{{ old('demo_url', $project->demo_url) }}" class="w-full rounded-2xl border-slate-200"></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Repo URL</label><input type="url" name="repo_url" value="{{ old('repo_url', $project->repo_url) }}" class="w-full rounded-2xl border-slate-200"></div>
    <div class="space-y-2"><label class="text-sm font-medium text-slate-700">Publish Date</label><input type="datetime-local" name="published_at" value="{{ old('published_at', optional($project->published_at)->format('Y-m-d\\TH:i')) }}" class="w-full rounded-2xl border-slate-200"></div>
    <div class="flex items-center gap-3 pt-8"><input type="hidden" name="is_featured" value="0"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $project->is_featured)) class="rounded border-slate-300"><label class="text-sm font-medium text-slate-700">Tampilkan sebagai featured project</label></div>
</div>
<div class="mt-8 flex gap-3"><button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-medium text-white">Simpan</button><a href="{{ route('admin.projects.index') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-medium text-slate-700">Batal</a></div>
